# Generated by Django 2.0.3 on 2018-03-22 05:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotName', models.CharField(max_length=64, unique=True)),
                ('lastConnect', models.DateTimeField(default=datetime.datetime(2018, 3, 22, 5, 1, 39, 2023, tzinfo=utc))),
                ('spotCount', models.IntegerField(default=0)),
                ('spotlimit', models.IntegerField(default=0)),
                ('open', models.BooleanField(default=False)),
                ('currentCapacity', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inUse', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('lastConnect', models.DateTimeField(default=datetime.datetime(2018, 3, 22, 5, 1, 39, 2670, tzinfo=utc))),
                ('ipAddr', models.CharField(default='', max_length=15)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
