# Generated by Django 2.0.2 on 2018-02-13 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_lot_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='occupied',
            new_name='in_use',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='lot',
            name='current_capacity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lot',
            name='host_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='lot',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 23, 23, 33, 412621, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lot',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='lot',
            name='spot_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='spot_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='ip_addr',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='spot',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 23, 23, 33, 413145, tzinfo=utc)),
        ),
    ]
