# Generated by Django 2.0.2 on 2018-02-14 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180213_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 1, 44, 31, 908064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spot',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 1, 44, 31, 908628, tzinfo=utc)),
        ),
    ]
