# Generated by Django 2.0.2 on 2018-02-15 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180214_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=200)),
                ('host_name', models.CharField(default='', max_length=60)),
                ('owner', models.CharField(default='', max_length=60)),
                ('last_connect', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 18, 13, 56, 931035, tzinfo=utc))),
                ('spot_count', models.IntegerField(default=0)),
                ('spot_limit', models.IntegerField(default=0)),
                ('open', models.BooleanField(default=False)),
                ('current_capacity', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('last_connect', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 18, 13, 56, 931600, tzinfo=utc))),
                ('ip_addr', models.CharField(default='', max_length=15)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Host')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='lot',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
